service: user-managment # NOTE: update this with your service name

custom: 
  PATH: ./config.json
  PROJECT: ${file(${self:custom.PATH}):project}

provider:
  name: aws
  runtime: nodejs8.10

  stage: ${opt:stage, 'dev'}
  region: ${file(${self:custom.PATH}):region, 'ap-southeast-1'}
  profile: ${file(${self:custom.PATH}):profile, 'default'}

  logRetentionInDays: ${file(${self:custom.PATH}):logRetentionInDays , 90}
  memorySize: ${file(${self:custom.PATH}):memorySize, 128}
  timeout: ${file(${self:custom.PATH}):timeout}
  
  stackName: ${self:custom.PROJECT}-stack
  apiName: ${self:custom.PROJECT}-api
  deploymentBucket:
    name: ${self:custom.PROJECT}-deployment-bucket

functions:
  hello:
    handler: handler.hello
    events:
      - http: get ${self:service}/hello